Cleanup logging (remove ALL color handling completely)

diff --git a/support/argv b/support/argv
--- a/support/argv
+++ b/support/argv
@@ -25,13 +25,13 @@ if [ "$previous_version" != "$version" ]; then
     [ -z "$previous_version" ] && previous_version="Unknown"
 
     #UPDATE REPORT
-    printf "%s\n" "> ${GREEN}updated${NC} $(basename "$0") (v. $previous_version) -> (v. $version)..."
+    printf "%s\n" "> updated $(basename "$0") (v. $previous_version) -> (v. $version)..."
 
     #RECORD UPDATED VERSION
     printf "%s\n" "$version" > ".previous_version"
 else
     #STANDARD RUN
-    printf "%s\n" "> ${GREEN}starting${NC} $(basename "$0") (v. $version)..."
+    printf "%s\n" "> starting $(basename "$0") (v. $version)..."
 fi
 
 # ----------------------------------------------------------------------------------------
@@ -125,17 +125,17 @@ while getopts "h?vfFbut:EgSRCmrsVadxD:c:" opt; do
             ;;
 
         r)  PREF_PERIODIC_MODE=true
-            printf "%s\n" "> ${ORANGE}warning:${NC} periodic scan mode may cause interference with 2.4GHz networks if run on a Raspberry Pi"
+            printf "%s\n" "> warning: periodic scan mode may cause interference with 2.4GHz networks if run on a Raspberry Pi"
             ;;
         v)
             printf "%s\n" "$VERSION"
             exit 0
             ;;
         F)
-            PREF_FILTER_DEBUG_LOGGING=true && printf "%s\n" "> ${ORANGE}warning:${NC} filter logging is enabled. this setting is only for informational and debug purposes"
+            PREF_FILTER_DEBUG_LOGGING=true && printf "%s\n" "> warning: filter logging is enabled. this setting is only for informational and debug purposes"
             ;;
         V)
-            PREF_VERBOSE_LOGGING=true && printf "%s\n" "> ${ORANGE}warning:${NC} verbose logging is enabled. this setting is only for informational and debugging purposes"
+            PREF_VERBOSE_LOGGING=true && printf "%s\n" "> warning: verbose logging is enabled. this setting is only for informational and debugging purposes"
             ;;
         c)
             #GET TARGET MAC ADDRESS
@@ -156,7 +156,7 @@ while getopts "h?vfFbut:EgSRCmrsVadxD:c:" opt; do
             return_data=$(hcitool cc $target_mac 2>&1 && hcitool auth $target_mac 2>&1 && hcitool dc $target_mac 2>&1)
 
             #ERROR REPORTING
-            [[ $return_data =~ .*error.* ]] && printf "%s\n" "> ${RED}error: ${NC}connection to $target_mac failed" || printf "%s\n" "> connection created to $target_mac"
+            [[ $return_data =~ .*error.* ]] && printf "%s\n" "> error: connection to $target_mac failed" || printf "%s\n" "> connection created to $target_mac"
 
             exit 0
             ;;
@@ -191,14 +191,14 @@ while getopts "h?vfFbut:EgSRCmrsVadxD:c:" opt; do
                     ;;
                 da|ad|rda|rad|dra|ard|dar|adr) PREF_TRIGGER_MODE_ARRIVE=true && PREF_TRIGGER_MODE_DEPART==true && $PREF_VERBOSE_LOGGING && printf "%s\n" "> trigger mode: scan only (both on arrive and depart) on trigger"
                     ;;
-                *) printf "%s\n" "> ${ORANGE}warning: ${NC}unknown trigger mode: $OPTARG"
+                *) printf "%s\n" "> warning: unknown trigger mode: $OPTARG"
                 ;;
             esac
             ;;
         a)  PREF_REPORT_ALL_MODE=true && $PREF_VERBOSE_LOGGING && printf "%s\n" "> report all scan results mode enabled"
             ;;
         D)  PREF_CONFIG_DIR=$OPTARG && printf "%s\n" "> using custom config directory [$PREF_CONFIG_DIR]"
-            [ ! -d "$PREF_CONFIG_DIR" ] && printf "%s\n" "> ${RED}error: ${NC}config directory [$PREF_CONFIG_DIR] doesn't exist" && exit 1
+            [ ! -d "$PREF_CONFIG_DIR" ] && printf "%s\n" "> error: config directory [$PREF_CONFIG_DIR] doesn't exist" && exit 1
                 ;;
         *)    printf "%s\n" "> unknown or depreciated argument: $opt"
     esac
diff --git a/support/btle b/support/btle
--- a/support/btle
+++ b/support/btle
@@ -38,7 +38,7 @@ btle_scanner () {
         #PUBLISH ERRORS BACK TO MAIN LOOP
         if [ -n "$error" ]; then
 
-            (>&2 log "${GREEN}[CMD-INFO]${NC}    cycling bluetooth hardware on $PREF_HCI_DEVICE. please wait a moment...")
+            (>&2 log "[CMD-INFO]    cycling bluetooth hardware on $PREF_HCI_DEVICE. please wait a moment...")
 
             #POWER CYCLE
             hciconfig $PREF_HCI_DEVICE down
@@ -252,38 +252,38 @@ btle_text_processor () {
         if [ ${PREF_FILTER_DEBUG_LOGGING:-false} == true ]; then
 
             #FORMATTING FOR FUN AND PROFIT
-               [[ ${flags,,} =~ ${PREF_FAIL_FILTER_ADV_FLAGS_ARRIVE,,} ]] && flag_filter_color=${RED} || flag_filter_color=${GREEN}
-               [[ ${manufacturer,,} =~ ${PREF_FAIL_FILTER_MANUFACTURER_ARRIVE,,} ]] && mfcg_filter_color=${RED} || mfcg_filter_color=${GREEN}
-            [[ ${flags,,} =~ ${PREF_PASS_FILTER_ADV_FLAGS_ARRIVE,,} ]] && flag_pass_filter_color=${GREEN} || flag_pass_filter_color=${RED}
-               [[ ${manufacturer,,} =~ ${PREF_PASS_FILTER_MANUFACTURER_ARRIVE,,} ]] && mfcg_pass_filter_color=${GREEN} || mfcg_pass_filter_color=${RED}
-               [[ ${pdu_type,,} =~ ${PREF_PASS_FILTER_PDU_TYPE,,} ]] && pdut_filter_color=${GREEN} || pdut_filter_color=${RED}
+               [[ ${flags,,} =~ ${PREF_FAIL_FILTER_ADV_FLAGS_ARRIVE,,} ]] && flag_filter_color= || flag_filter_color=
+               [[ ${manufacturer,,} =~ ${PREF_FAIL_FILTER_MANUFACTURER_ARRIVE,,} ]] && mfcg_filter_color= || mfcg_filter_color=
+            [[ ${flags,,} =~ ${PREF_PASS_FILTER_ADV_FLAGS_ARRIVE,,} ]] && flag_pass_filter_color= || flag_pass_filter_color=
+               [[ ${manufacturer,,} =~ ${PREF_PASS_FILTER_MANUFACTURER_ARRIVE,,} ]] && mfcg_pass_filter_color= || mfcg_pass_filter_color=
+               [[ ${pdu_type,,} =~ ${PREF_PASS_FILTER_PDU_TYPE,,} ]] && pdut_filter_color= || pdut_filter_color=
 
                #REASSEMBLE FULL
                full_packet=$(echo "$packet" | tr "~" "\n")
 
             #PRINT DEBUG MESSAGES
-            printf "\n%s\n" "${PURPLE}***************** ARRIVE/REJECT FILTER DEBUG ********************** ${NC}"
+            printf "\n%s\n" "${PURPLE}***************** ARRIVE/REJECT FILTER DEBUG ********************** "
             printf "%s\n" "btmon packet:"
             printf "%s\n" "$full_packet"
-            printf "%s\n" "flag pass:    ${flag_pass_filter_color}only (${PREF_PASS_FILTER_ADV_FLAGS_ARRIVE,,})${NC}"
-            printf "%s\n" "mfcg pass:    ${mfcg_pass_filter_color}only (${PREF_PASS_FILTER_MANUFACTURER_ARRIVE,,})${NC}"
-            printf "%s\n" "flag fail:    ${flag_filter_color}not (${PREF_FAIL_FILTER_ADV_FLAGS_ARRIVE,,})${NC}"
-            printf "%s\n" "mfcg fail:    ${mfcg_filter_color}not (${PREF_FAIL_FILTER_MANUFACTURER_ARRIVE,,})${NC}"
-            printf "%s\n" "pdu filter:     ${pdut_filter_color}only (${PREF_PASS_FILTER_PDU_TYPE,,})${NC}"
-            [ -n "${blacklisted_devices["$received_mac_address"]}" ] && printf "%s\n" "blacklist:     ${RED}true${NC}" || printf "%s\n" "blacklist:     ${GREEN}false${NC}"
+            printf "%s\n" "flag pass:    ${flag_pass_filter_color}only (${PREF_PASS_FILTER_ADV_FLAGS_ARRIVE,,})"
+            printf "%s\n" "mfcg pass:    ${mfcg_pass_filter_color}only (${PREF_PASS_FILTER_MANUFACTURER_ARRIVE,,})"
+            printf "%s\n" "flag fail:    ${flag_filter_color}not (${PREF_FAIL_FILTER_ADV_FLAGS_ARRIVE,,})"
+            printf "%s\n" "mfcg fail:    ${mfcg_filter_color}not (${PREF_FAIL_FILTER_MANUFACTURER_ARRIVE,,})"
+            printf "%s\n" "pdu filter:     ${pdut_filter_color}only (${PREF_PASS_FILTER_PDU_TYPE,,})"
+            [ -n "${blacklisted_devices["$received_mac_address"]}" ] && printf "%s\n" "blacklist:     true" || printf "%s\n" "blacklist:     false"
             printf "%s\n" ""
-            printf "%s\n" "type:         ${CYAN}${tx_type:-???}${NC}"
-            printf "%s\n" "mac:         ${CYAN}${received_mac_address:-???}${NC}"
-            printf "%s\n" "name:         ${CYAN}${gap_name_str:-???}${NC}"
-            printf "%s\n" "pdu:         ${CYAN}${pdu_type:-???}${NC}"
-            printf "%s\n" "type:         ${CYAN}${device_type:-???}${NC}"
-            printf "%s\n" "oem:         ${CYAN}${oem_data:-???}${NC}"
-            printf "%s\n" "rssi:         ${CYAN}${rssi_value:-???} dBm${NC}"
-            printf "%s\n" "flags:        ${CYAN}${flags:-???}${NC}"
-            printf "%s\n" "hex:        ${CYAN}${hex_data:-???}${NC}"
-            printf "%s\n" "resolvable:    ${CYAN}${resolvable:-???}${NC}"
-            printf "%s\n" "man: ${CYAN}        ${manufacturer:-???}${NC}"
-            printf "%s\n" "time: ${CYAN}        ${timestamp:-???}${NC}"
+            printf "%s\n" "type:         ${tx_type:-???}"
+            printf "%s\n" "mac:         ${received_mac_address:-???}"
+            printf "%s\n" "name:         ${gap_name_str:-???}"
+            printf "%s\n" "pdu:         ${pdu_type:-???}"
+            printf "%s\n" "type:         ${device_type:-???}"
+            printf "%s\n" "oem:         ${oem_data:-???}"
+            printf "%s\n" "rssi:         ${rssi_value:-???} dBm"
+            printf "%s\n" "flags:        ${flags:-???}"
+            printf "%s\n" "hex:        ${hex_data:-???}"
+            printf "%s\n" "resolvable:    ${resolvable:-???}"
+            printf "%s\n" "man:         ${manufacturer:-???}"
+            printf "%s\n" "time:         ${timestamp:-???}"
             printf "%s\n" ""
         fi
 
